export default {
  "fontFamilyDisplay": "Circuit",
  "fontFamilyDisplayOutline": "Circuit Outline",
  "fontFamilyText": "TT Norms",
  "fontSizeMedium": 18,
  "fontSizeHeaderSmall": 28,
  "fontSizeLarge": 20,
  "fontSizeRegular": 16,
  "fontSizeTiny": 12,
  "fontSizeMobileDisplayTiny": 22,
  "fontSizeMobileDisplay": 36,
  "fontSizeDesktopDisplaySmall": 42,
  "fontSizeDesktopDisplay": 68,
  "fontSizeDesktopDisplayTiny": 28,
  "fontSizeMobileDisplaySmall": 28,
  "fontSizeSmall": 14,
  "fontSizeDesktopDisplayJumbo": 100,
  "fontSizeHuge": 24,
  "fontSizeHeader": 32,
  "fontSizeHeaderLarge": 36,
  "fontSizeMobileDisplayJumbo": 54,
  "fontWeightRegular": "400",
  "fontWeightMedium": "500",
  "fontWeightBold": "700",
  "lineHeightLarge": 28,
  "lineHeightDesktopDisplay": 72,
  "lineHeightRegular": 24,
  "lineHeightDesktopDisplayTiny": 32,
  "lineHeightMobileDisplaySmall": 32,
  "lineHeightMobileDisplay": 40,
  "lineHeightMobileDisplayTiny": 30,
  "lineHeightDesktopDisplaySmall": 44,
  "lineHeightHuge": 32,
  "lineHeightHeader": 36,
  "lineHeightMobileDisplayJumbo": 58,
  "lineHeightSmall": 19,
  "lineHeightDesktopDisplayJumbo": 108,
  "lineHeightMedium": 24,
  "lineHeightHeaderLarge": 40,
  "lineHeightTiny": 16,
  "lineHeightHeaderSmall": 32,
  "colorGreen": "#00af7c",
  "colorGray60": "#999999",
  "colorGray50": "#bdbdbd",
  "colorGray40": "#d6d6d6",
  "colorGray30": "#e7e7e7",
  "colorGray20": "#efefef",
  "colorBrand": "#0055ff",
  "colorRedDark": "#8c2a39",
  "colorOrangeLight": "#fed6cb",
  "colorGray10": "#f7f7f7",
  "colorWhite": "#ffffff",
  "colorOrangeDark": "#9d432a",
  "colorRedLight": "#ffb7c2",
  "colorYellowDark": "#9e8f2e",
  "colorRed": "#c91630",
  "opacityDarker": 0.15,


  "colorBrandLive": "#d83945",

  "colorOrange": "#fa5b30",
  "colorBrandLight": "#46a0ff",



  "colorGreenDark": "#007050",

  "colorDivider": "#e3e3e3",
  "colorGreenLight": "#99dfcb",
  "colorYellow": "#eec200",
  "colorBrandDark": "#004488",
  "colorGray90": "#333333",
  "colorGray80": "#555555",
  "colorYellowLight": "#fce172",
  "colorGray70": "#7f7f7f",
  "spacingMega": 48,
  "spacingHuge": 32,
  "spacingLarge": 24,
  "spacingRegular": 16,
  "spacingSmall": 8,
  "spacingTiny": 4,
  "sizeIconWidth": 24,
  "sizeIconHeight": 24,
  "radiusRegular": 3
}
